trustly_case:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      port: 5432
      user: abner_rodrigues
      pass: abner
      dbname: trustly
      schema: public
      threads: 8
    prod: 
      type: postgres
      host: localhost
      port: 5432
      user: abner_rodrigues
      pass: abner
      dbname: trustly
      schema: public
      threads: 8
  target: dev