trustly_case:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: /Users/abner.rodrigues/Documents/projects/trustly/case-trustly/database/database.db
      schema: 'dev'
      threads: 8
    prod: 
      type: duckdb
      path: /Users/abner.rodrigues/Documents/projects/trustly/case-trustly/database/database.db
      schema: 'prod'
      threads: 8
  target: dev


